# Assignment Day 3

# Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np
ary = np.arange(2, 50, 3)
print(ary)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [4]:
import numpy as np
lt_1 = []
lt_2 = []
for i in range(5):
  x=int(input("Enter the value for list 1 :- "))
  lt_1.append(x)
for i in range(5):
  y=int(input("Enter the value for list 2 :- "))
  lt_2.append(y)
ary_1 = np.array(lt_1)
ary_2 = np.array(lt_2)
ary = np.concatenate((ary_1, ary_2))
print("Array value after concatenated arrays :-",ary)
sortedAry = np.sort(ary)
print("Sorted Array of concatenated array :-",sortedAry)

Enter the value for list 1 :- 0
Enter the value for list 1 :- 7
Enter the value for list 1 :- 4
Enter the value for list 1 :- 10
Enter the value for list 1 :- 8
Enter the value for list 2 :- 1
Enter the value for list 2 :- 5
Enter the value for list 2 :- 2
Enter the value for list 2 :- 6
Enter the value for list 2 :- 3
Array value after concatenated arrays :- [ 0  7  4 10  8  1  5  2  6  3]
Sorted Array of concatenated array :- [ 0  1  2  3  4  5  6  7  8 10]


# Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.

In [6]:
import numpy as np
#2Dimensional Array
ary = np.array([[4,5,6],[5,1,3]])
#syntax for finding dimension: ArrayName.ndim
print("Dimensions of array :- ", ary.ndim)
#syntax for finding size: ArrayName.size
print("Size of array :- ", ary.size)

Dimensions of array :-  2
Size of array :-  6


# Questions 4:

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [9]:
import numpy as np
ary = np.arange(20)
print("Shape of Array :",ary.shape)
row_ary = ary[np.newaxis, :]
print("Shape of 2d Array in row major :",row_ary.shape)
col_ary = ary[:, np.newaxis]
print("Shape of 2d Array in column major :",col_ary.shape)

Shape of Array : (20,)
Shape of 2d Array in row major : (1, 20)
Shape of 2d Array in column major : (20, 1)


# Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [11]:
import numpy as np
ary_1 = np.square([6, 7, 8])
ary_2 = np.square([1, 2, 3])
print("Horizontal Append :", np.hstack((ary_1, ary_2)))
print("Vertical Append :", np.vstack((ary_1, ary_2)))

Horizontal Append : [36 49 64  1  4  9]
Vertical Append : [[36 49 64]
 [ 1  4  9]]


# Questions 6:
How to get unique items and counts of unique items?

In [12]:
import numpy as np

ary_1 = np.array([1,4,5,10,8,4,5,16,25,12,45,25])
unique, counts = np.unique(ary_1, return_counts=True)
ary = np.asarray((unique, counts)).T
print(ary)

[[ 1  1]
 [ 4  2]
 [ 5  2]
 [ 8  1]
 [10  1]
 [12  1]
 [16  1]
 [25  2]
 [45  1]]
